source 'https://cdn.cocoapods.org/'  
  
platform :ios, '14.0' 
inhibit_all_warnings!  
  
workspace 'PexelsDemo'
project 'MyPexels.xcodeproj'

target 'MyPexels (iOS)' do 
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'  
end  
  
target 'Tests iOS' do  
  pod 'RxBlocking', '~> 6.5.0' 
  pod 'RxTest', '~> 6.5.0'  
end